parserOptions:
  ecmaVersion: 6
  project:
    - tsconfig.json
env:
  browser: true

extends:
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended

rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
    
